name: CI
on: [push]
env:
  CI: 'true'
jobs:
  tests:
    strategy:
      matrix:
        java: [11,14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: ci tests java-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - run: cd $GITHUB_WORKSPACE && ./mvnw
  basic-plain-html:
    strategy:
      matrix:
        java: [11,14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: basic plain html (no template) java-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - run: sudo apt-get install --fix-missing httpie
    - run: cd $GITHUB_WORKSPACE && ./mvnw -f basic-plain-html
    - run: java -jar $GITHUB_WORKSPACE/basic-plain-html/target/*jar &
    - run: sleep 2s
    - run: http get :8080/api404
    - run: http get :8080/not-found
  markdown-commonmark:
    strategy:
      matrix:
        java: [11,14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: atlassian commonmark template java-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - run: sudo apt-get install --fix-missing httpie
    - run: cd $GITHUB_WORKSPACE && ./mvnw -f markdown-commonmark
    - run: java -jar $GITHUB_WORKSPACE/markdown-commonmark/target/*jar &
    - run: sleep 2s
    - run: http get :8080/api
    - run: http get :8080
  markdown-flexmark-java:
    strategy:
      matrix:
        java: [11,14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: flexmark-java template java-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - run: sudo apt-get install --fix-missing httpie
    - run: cd $GITHUB_WORKSPACE && ./mvnw -f markdown-flexmark-java
    - run: java -jar $GITHUB_WORKSPACE/markdown-flexmark-java/target/*jar &
    - run: sleep 2s
    - run: http get :8080/api
    - run: http get :8080
  markdown-txtmark:
    strategy:
      matrix:
        java: [11,14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: txtmark template java-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - run: sudo apt-get install --fix-missing httpie
    - run: cd $GITHUB_WORKSPACE && ./mvnw -f markdown-txtmark
    - run: java -jar $GITHUB_WORKSPACE/markdown-txtmark/target/*jar &
    - run: sleep 2s
    - run: http get :8080/api
    - run: http get :8080
  markdown-pegdown:
    strategy:
      matrix:
        java: [11,14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: pegdown template java-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - run: sudo apt-get install --fix-missing httpie
    - run: cd $GITHUB_WORKSPACE && ./mvnw -f markdown-pegdown
    - run: java -jar $GITHUB_WORKSPACE/markdown-pegdown/target/*jar &
    - run: sleep 2s
    - run: http get :8080/api
    - run: http get :8080
  markdown-markdownpapers:
    strategy:
      matrix:
        java: [11,14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: markdownpapers template java-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - run: sudo apt-get install --fix-missing httpie
    - run: cd $GITHUB_WORKSPACE && ./mvnw -f markdown-markdownpapers
    - run: java -jar $GITHUB_WORKSPACE/markdown-markdownpapers/target/*jar &
    - run: sleep 2s
    - run: http get :8080/api
    - run: http get :8080
  markdown-markdownj:
    strategy:
      matrix:
        java: [11,14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: markdownj template java-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - run: sudo apt-get install --fix-missing httpie
    - run: cd $GITHUB_WORKSPACE && ./mvnw -f markdown-markdownj
    - run: java -jar $GITHUB_WORKSPACE/markdown-markdownj/target/*jar &
    - run: sleep 2s
    - run: http get :8080/api
    - run: http get :8080
